# Generated by Django 6.0.3 on 2026-06-01 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('color_piel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manicurista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('especialidad', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('total', models.IntegerField()),
                ('estado', models.CharField(choices=[('Pendiente', 'PENDIENTE'), ('Confirmada', 'CONFIRMADA'), ('Cancelada', 'CANCELADA')], default='Pendiente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.clientes')),
                ('manicurista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.manicurista')),
                ('servicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.servicios')),
            ],
        ),
    ]
