# Generated by Django 6.0.3 on 2026-06-01 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manicurista',
            name='estado',
            field=models.CharField(choices=[('Activa', 'ACTIVA'), ('Inactiva', 'INACTIVA')], default='Activa', max_length=20),
        ),
        migrations.AddField(
            model_name='manicurista',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date(2026, 5, 31)),
            preserve_default=False,
        ),
    ]
