# Generated by Django 6.0.3 on 2026-06-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_manicurista_estado_manicurista_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='duracion',
            field=models.IntegerField(default=60, help_text='Duracion en minutos'),
            preserve_default=False,
        ),
    ]
