# Generated by Django 6.0.3 on 2026-06-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_servicios_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manicurista',
            name='especialidad',
            field=models.CharField(max_length=100),
        ),
    ]
