# Generated by Django 6.0.3 on 2026-06-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_manicurista_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('precio_compra', models.IntegerField()),
                ('fecha_compra', models.DateField()),
            ],
        ),
    ]
