# Generated by Django 6.0.5 on 2026-06-02 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_pagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('metodo_pago', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Pendiente', 'PENDIENTE'), ('Realizado', 'REALIZADO')], default='Pendiente', max_length=20)),
                ('valor', models.IntegerField()),
                ('citas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.citas')),
            ],
        ),
    ]
