# Generated by Django 6.0.6 on 2026-06-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_gastos_recibo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'PENDIENTE'), ('Realizado', 'REALIZADO'), ('Fallido', 'FALLIDO')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='metodo_pago',
            field=models.CharField(choices=[('Wompi', 'WOMPI'), ('Mercado Pago', 'MERCADO PAGO'), ('Transferencia', 'TRANSFERENCIA')], max_length=50),
        ),
    ]
