# Generated by Django 6.0.6 on 2026-06-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_pagos_referencia_alter_pagos_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='password',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manicurista',
            name='password',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
