# Generated by Django 6.0.6 on 2026-07-03 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_clientes_password_manicurista_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='estado',
        ),
    ]
