# Generated by Django 4.2.23 on 2026-08-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_rol_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='estado',
            field=models.CharField(choices=[('Activo', 'ACTIVO'), ('Inactivo', 'INACTIVO')], default='Activo', max_length=8),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
