# Generated by Django 6.1 on 2026-08-20 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_servicios_estado_alter_servicios_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='color_piel',
        ),
        migrations.AddField(
            model_name='clientes',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manicurista',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manicurista', to=settings.AUTH_USER_MODEL),
        ),
    ]
