# Generated by Django 6.1 on 2026-08-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_remove_clientes_color_piel_clientes_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AddField(
            model_name='manicurista',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
