# Generated by Django 6.1 on 2026-08-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0014_clientes_foto_perfil_manicurista_foto_perfil'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='citas',
            constraint=models.UniqueConstraint(fields=('manicurista', 'fecha', 'hora'), name='unique_manicurista_fecha_hora'),
        ),
    ]
