# Generated by Django 6.1 on 2026-08-31 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0016_citas_estado_resena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='fecha_compra',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='citas',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='valor',
        ),
        migrations.AddField(
            model_name='inventario',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True, default='2026-08-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibo',
            name='pago',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recibo', to='agenda.pagos'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='citas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='agenda.citas'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='metodo_pago',
            field=models.CharField(choices=[('Efectivo', 'EFECTIVO'), ('Nequi', 'NEQUI'), ('Bancolombia', 'BANCOLOMBIA'), ('Transferencia', 'TRANSFERENCIA')], max_length=50),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Entrada', 'ENTRADA'), ('Salida', 'SALIDA')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='agenda.inventario')),
            ],
        ),
    ]
