# Generated by Django 6.1 on 2026-08-31 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0017_remove_inventario_fecha_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='pago',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recibo', to='agenda.pagos'),
            preserve_default=False,
        ),
    ]
