# Generated by Django 6.1.1 on 2026-09-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0019_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inventario/'),
        ),
    ]
