# Generated by Django 6.1.1 on 2026-09-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0020_inventario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Esmaltes y Geles', 'Esmaltes y Geles'), ('Sistemas Artificiales', 'Sistemas Artificiales'), ('Herramientas', 'Herramientas'), ('Decoraciones', 'Decoraciones'), ('Preparadores', 'Preparadores')], default='Esmaltes', max_length=50, null=True),
        ),
    ]
