# Generated by Django 6.1.1 on 2026-09-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0022_solicitudsoporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='porcentaje_comision',
            field=models.IntegerField(default=50, help_text='Porcentaje de comisión para la manicurista'),
        ),
    ]
